FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=development
RUN npm install -g @nestjs/cli ts-node
COPY backend/package*.json ./
RUN npm install
COPY backend/ .
COPY schema/ ./schema/
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
